#page title
page_title                                : "Ivy: Productivity App"                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : "https://apps.apple.com/us/app/ivy-productivity-app/id6744418405"                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "Ivy: Productivity App"                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your daily to-dos, made simple.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 : Washington, D.C.                                
email_address                             : 
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : "Daily Planning, Simplified"
    description                           : "Based on the Ivy Lee Method: plan six high-impact tasks each day for focused, clutter-free productivity."
    fontawesome_icon_name                 : list
    
  - title                                 : "One-Tap Task Flow"
    description                           : "Check off tasks, tap to edit, and stay in motion—all from a single, intuitive screen."
    fontawesome_icon_name                 : mobile

  - title                                 : "Gentle Nudges, Not Notifications"
    description                           : "Stay on track with streaks and subtle reminders designed to motivate, not overwhelm."
    fontawesome_icon_name                 : bell

  - title                                 : "No Logins. No Clutter."
    description                           : "Your tasks live securely on your device—no accounts, syncing, or distractions."
    fontawesome_icon_name                 : user

  - title                                 : "Delightfully Minimal Design"
    description                           : "A calm, elegant interface with zero learning curve. Everything you need, nothing you don’t."
    fontawesome_icon_name                 : mountain
  
  - title                                 : "Insightful Progress Cues"
    description                           : "See how often you finish your list, when you're most productive, and how your focus is improving—no spreadsheets needed."
    fontawesome_icon_name                 : chart-line

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#146683"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#bfe9ff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000" #"#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
